version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:10

    working_directory: ~/plugin

    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: install yarn
          command: 'sudo npm install -g yarn --quiet'
      - run:
          name: install dependencies
          command: 'yarn install --pure-lockfile'
      - run:
          name: Run Toolkit Build
          command: 'npx grafana-toolkit plugin:ci-build'
      - run:
          name: Bundle Plugin
          command: 'npx grafana-toolkit plugin:ci-bundle'
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - store_artifacts:
          path: ci/artifacts
